# Bria Stalker
## WK10 03/24/2021
### NumPy Intro

In [2]:
import numpy as np
#import libaray under name 'np'

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "c:\Miniconda\envs\py37_default\python.exe"
  * The NumPy version is: "1.18.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.


In [3]:
np.__version__

'1.18.5'

In [5]:
arr = np.array([1,2,3,4,5,6])

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array((1,2,3,4,5,6))

In [10]:
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
#0 dimension (0-D) Arrays
arr2 = np.array(50)

In [13]:
arr2

array(50)

In [14]:
print(arr2)

50


In [15]:
# 1 dimension (1-D) arrays (most common)
arr3 = np.array([1,2,3,4,5,6])

In [16]:
print(arr3)

[1 2 3 4 5 6]


In [17]:
#2 dimesnion (2-D) array...Matrix

arr4 = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [19]:
# 3 dimension 3-D array

arr5 = np.array([ [[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]] ])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [20]:
#ndim gives number of dimensions
print(arr2.ndim)

0


In [21]:
print(arr3.ndim)

1


In [22]:
print(arr4.ndim)

2


In [23]:
print(arr5.ndim)

3


In [24]:
#Array Indexing -
print(arr3[1])

2


In [25]:
print(arr3[-1])

6


In [26]:
#gives sum of value at given idex
print(arr3[0] + arr3[3])

5


In [27]:
# 2D Access - Indexing
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [28]:
print(arr4[0,1])

2


In [29]:
print(arr4[1,-1])

66


In [30]:
print(arr4[1,3])

44


In [31]:
# 3D Access - indexing
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [32]:
print(arr5[0,1,1])

5


In [33]:
print(arr5[1,0,-1])

33


In [34]:
#hard code number of dimensions
marr = np.array([1,2,3,4,5], ndmin=5)

In [35]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [36]:
marr.ndim

5

In [37]:
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [38]:
print(arr4[0,-1])

6


In [39]:
# Slicing NumPy Arrays
#[start:end]
#[start:end:step]
print(arr3)

[1 2 3 4 5 6]


In [40]:
print(arr3[1:4])

[2 3 4]


In [41]:
print(arr3[::-1])

[6 5 4 3 2 1]


In [42]:
print(arr3[3:])

[4 5 6]


In [45]:
print(arr3[:3])

[1 2 3]


In [48]:
print(arr3[-3:-1])

[4 5]


In [52]:
#Slicing with step
print(arr3[0:5:2])

[1 3 5]


In [54]:
print(arr3[0:5:3])

[1 4]


In [55]:
print(arr3[0:7:2])

[1 3 5]


In [56]:
#every other array element
print(arr3[::2])

[1 3 5]


In [58]:
#Slicing 2D Arrays
print(arr3.ndim)

1


In [59]:
print(arr4.ndim)

2


In [60]:
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [61]:
print(arr4[1,1:3])

[22 33]


In [62]:
print(arr4[0,1:3])

[2 3]


In [63]:
#gives index 3 element for both lists
print(arr4[0:2,3])

[ 4 44]


In [64]:
print(arr4[:,3])

[ 4 44]


In [65]:
print(arr4[:,1:3])

[[ 2  3]
 [22 33]]
