# Bria Stalker
## WK10 3/24/2021
### NumPy Array Processing

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]
print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [4]:
type(my_arr)

numpy.ndarray

In [5]:
print(my_arr.dtype)

int32


In [6]:
fruits =['Orange','Apple','Cherry','Lemon']

In [7]:
my_strArr = np.array(fruits)

In [8]:
print(my_strArr.dtype)

<U6


In [9]:
my_arr2 = np.array([11,22,33,44,55],dtype= 'S')

In [10]:
print(my_arr2.dtype)

|S2


In [11]:
my_arr2 = np.array([1,2,3,4,5],dtype= 'S')

In [12]:
print(my_arr2.dtype)

|S1


In [15]:
my_arr3 = np.array([5,6,7,8,9],dtype = 'i4')
print(my_arr3.dtype)

int32


In [16]:
my_errArr = np.array(['1','2','3'], dtype = 'i')

In [17]:
print(my_errArr)

[1 2 3]


In [18]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)

In [20]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [21]:
arr = my_arr.astype('i')

In [22]:
print(arr)

[78 88 90 89]


In [23]:
arr = np.array([1,0,0,4,5,6,7,0])
print(arr.dtype)

int32


In [24]:
bool_arr = arr.astype(bool)

In [26]:
print(bool_arr)
print(arr) # 0 is always false

[ True False False  True  True  True  True False]
[1 0 0 4 5 6 7 0]


In [27]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

In [28]:
my_list = [lst1,lst2]

In [29]:
my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [30]:
#NumPy Built in Functions to generate arrays from existing arrays
# Copy and View, instead of using =
my_list = [11,12,13,14,15]

arr = np.array(my_list)
c_arr = arr.copy() #Copy Array
print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [31]:
arr[3] = 4

In [32]:
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [37]:
my_list = [11,12,13,14,15]

arr = np.array(my_list)
v_arr = arr.view() #Copy Array
print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13  4 15]


In [38]:
arr[3] = 4

In [39]:
print(arr)
print(v_arr) # using view both orginal and copy change

[11 12 13  4 15]
[11 12 13  4 15]


In [40]:
print(c_arr.base)
print(v_arr.base)

[11 12 13  4 15]
[11 12 13  4 15]


In [41]:
#Shape gives the number of elements in each dimension


In [55]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.shape) 

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)


In [46]:
#2 is number of dimensions and 5 is number of elements in each dimension

In [52]:
arr = np.array(lst1, ndmin=4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [53]:
arr = np.array(lst1, ndmin=6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)
