# Bria Stalker
## WK11 04/4/2021
### Python Universal Functions

In [1]:
import numpy as np

In [3]:
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]
z = []
for i,j in zip(arr1,arr2): #zip joining lists
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [5]:
#zip

fname = ("alice","bob","christy")
lname = ("charley","clark","robert")
x = zip(fname,lname)
print(tuple(x))

(('alice', 'charley'), ('bob', 'clark'), ('christy', 'robert'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [9]:
import numpy as np

In [10]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
arr1 = np.random.randn(10)

In [15]:
arr1

array([ 2.87780044, -2.22912146, -1.15513953, -0.40854338, -0.77531607,
       -0.51168632,  1.23026508,  1.09591936,  0.58869368, -0.51471983])

In [16]:
arr2 = np.random.randn(10)
arr2

array([ 0.47375533,  0.7228915 , -0.08179967, -0.66189478, -0.19012672,
       -0.04616947,  1.49702174,  0.40885282,  0.19509026,  0.34975237])

In [19]:
np.add(arr1,arr2)

array([ 0.2912715 ,  0.87214334,  0.34696942, -0.71048195, -2.65033881,
       -0.81213812,  1.19907724, -1.00024687, -0.23895414, -0.32851843])

In [21]:
np.maximum(arr1,arr2)

array([ 0.47375533,  0.7228915 ,  0.42876909, -0.04858717, -0.19012672,
       -0.04616947,  1.49702174,  0.40885282,  0.19509026,  0.34975237])

In [22]:
#np.where
arr = np.arange(9).reshape(3,3)

In [23]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [27]:
print(np.where(arr < 4,-1,10)) #<4 is -1 >4 is 10

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [28]:
np.where((arr < 4) & (arr > 2), -1,2)

array([[ 2,  2,  2],
       [-1,  2,  2],
       [ 2,  2,  2]])

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [30]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [31]:
#Now using np.where
arr3 = np.where(arr_b,arr1,arr2)

In [32]:
arr3

array([ 1, 20,  3,  4, 50])