# Bria Stalker
## WK11 04/4/2021
### Python Universal Functions

In [1]:
import numpy as np

In [3]:
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]
z = []
for i,j in zip(arr1,arr2): #zip joining lists
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [5]:
#zip

fname = ("alice","bob","christy")
lname = ("charley","clark","robert")
x = zip(fname,lname)
print(tuple(x))

(('alice', 'charley'), ('bob', 'clark'), ('christy', 'robert'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [9]:
import numpy as np

In [10]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
arr1 = np.random.randn(10)

In [15]:
arr1

array([ 2.87780044, -2.22912146, -1.15513953, -0.40854338, -0.77531607,
       -0.51168632,  1.23026508,  1.09591936,  0.58869368, -0.51471983])

In [16]:
arr2 = np.random.randn(10)
arr2

array([ 0.47375533,  0.7228915 , -0.08179967, -0.66189478, -0.19012672,
       -0.04616947,  1.49702174,  0.40885282,  0.19509026,  0.34975237])

In [19]:
np.add(arr1,arr2)

array([ 0.2912715 ,  0.87214334,  0.34696942, -0.71048195, -2.65033881,
       -0.81213812,  1.19907724, -1.00024687, -0.23895414, -0.32851843])

In [21]:
np.maximum(arr1,arr2)

array([ 0.47375533,  0.7228915 ,  0.42876909, -0.04858717, -0.19012672,
       -0.04616947,  1.49702174,  0.40885282,  0.19509026,  0.34975237])

In [22]:
#np.where
arr = np.arange(9).reshape(3,3)

In [23]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [27]:
print(np.where(arr < 4,-1,10)) #<4 is -1 >4 is 10

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [28]:
np.where((arr < 4) & (arr > 2), -1,2)

array([[ 2,  2,  2],
       [-1,  2,  2],
       [ 2,  2,  2]])

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [30]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [31]:
#Now using np.where
arr3 = np.where(arr_b,arr1,arr2)

In [32]:
arr3

array([ 1, 20,  3,  4, 50])

In [4]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [7]:
np.where([[True,False],[True,True]], [[5,6],[7,8]],[[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [11]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.41895607, -0.83794854, -0.11952915],
       [ 1.8090859 ,  0.48863931,  0.37524589],
       [-1.09213497, -1.33904053,  1.00110118]])

In [13]:
np.where(arr<0,0,1) #0 is true, 1 is false

array([[0, 0, 0],
       [1, 1, 1],
       [0, 0, 1]])

In [14]:
arr_b=np.array([True,False,True,False,False])
arr_b.any() #checks if any elements are true

True

In [15]:
arr_b.all() #checks is all elements are true

False

In [16]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits) #remove duplicates in arrays

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [17]:
np.in1d(['Apple','Cherry','Grape'],fruits) #checks if these exist in array

array([ True,  True, False])

In [21]:
#statistical measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr.sum() #sum of all elements in the array

45

In [24]:
arr.sum(0) #sum of columns

array([12, 15, 18])

In [25]:
arr.sum(1) #sum of rows

array([ 6, 15, 24])

In [27]:
print(arr)
np.sum(arr,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [28]:
arr.mean()#average of array

5.0

In [29]:
arr.mean(0) #average of each column

array([4., 5., 6.])

In [30]:
arr.mean(1) #average of each row

array([2., 5., 8.])

In [32]:
np.mean(arr,axis=0)
np.mean(arr,axis=1)

array([2., 5., 8.])

In [33]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [34]:
arr.var() #variance of the array

6.666666666666667

In [35]:
arr.std() #standard deviation of the array

2.581988897471611

In [36]:
arr = np.array([3,6,7,9,5,4,2,11,56])

In [37]:
arr.sort() #sorts array numerically

In [38]:
arr

array([ 2,  3,  4,  5,  6,  7,  9, 11, 56])

In [39]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a = np.arange(25).reshape(5,5)

In [42]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [47]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape(2,2)
print(a)
a*i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [49]:
m = np.mat([[1,2],[3,4]]) #matrix
m

matrix([[1, 2],
        [3, 4]])

In [51]:
m*i

matrix([[1., 2.],
        [3., 4.]])

In [53]:
#transpose
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)
print('-----------')
t = arr.T #Flip rows and columns
t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
-----------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [57]:
arr_3d = np.arange(20).reshape((2,5,2))#2*2*5 is 20

In [58]:
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [59]:
arr_3d.transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [60]:
arr_3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [61]:
arr_3d.transpose(2,1,0)

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [62]:
np.random.random((4,4))

array([[0.96026044, 0.63285991, 0.67765077, 0.64866339],
       [0.805853  , 0.77723565, 0.03628429, 0.49952937],
       [0.58258104, 0.54703596, 0.16546084, 0.41911102],
       [0.50687206, 0.56843205, 0.81393689, 0.51880163]])

In [64]:
from numpy.random import random
random((4,4))

array([[0.76665043, 0.9373457 , 0.4192201 , 0.89438265],
       [0.55750262, 0.95616691, 0.72697281, 0.65419684],
       [0.32789901, 0.00392253, 0.41000456, 0.42026174],
       [0.98533988, 0.60551266, 0.61473945, 0.01171182]])

In [65]:
from numpy.random import randn
randn(5,5)

array([[ 1.22801461, -0.3357899 ,  0.44557824, -0.66105864,  0.8259235 ],
       [ 0.62369078,  0.40266864, -0.39345232,  0.26545837, -0.6931082 ],
       [ 1.58858176, -0.61694555,  0.23530053,  0.85357438,  0.60808675],
       [-0.64203738, -0.46713852,  0.37664348,  0.69745567, -1.07157357],
       [ 1.14910757,  1.12987376, -1.16980067,  2.44751724, -0.48709088]])

In [67]:
randn(5)

array([ 1.52900355,  1.15156462,  0.0892406 ,  0.14409627, -0.68445665])

In [69]:
np.random.randint(10,50)

16

In [72]:
website = "https://dosc.scipy.org/doc/numpy/reference/ufuncs.html#availble-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [73]:
webbrowser.open(website)

True

In [74]:
import pandas as pd #importing pandas